site_name: Testronaut
site_description: AI-assisted testing tool for command-line applications
site_url: https://yourusername.github.io/testronaut/
repo_url: https://github.com/yourusername/testronaut
repo_name: yourusername/testronaut

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_bases: true
            show_signature_annotations: true
            heading_level: 3

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Getting Started:
      - Installation: guides/installation.md
      - Quick Start: guides/quickstart.md
  - User Guide:
      - Core Concepts: guides/concepts.md
      - CLI Reference: reference/cli.md
      - Configuration: reference/configuration.md
  - API Reference:
      - Overview: api/overview.md
      - Core API: api/core.md
      - CLI: api/cli.md
      - Models: api/models.md
  - Contributing:
      - Guidelines: contributing/guidelines.md
      - Development: contributing/development.md
