# Testronaut default configuration

app_name: Testronaut
debug: false
config_dir: ~/.testronaut

# Logging settings
logging:
  level: INFO
  format: structured
  output_file: null
  json_output: false

# Database settings
database:
  url: sqlite:///testronaut.db
  echo: false
  pool_size: 5
  pool_recycle: 3600

# LLM settings
llm:
  provider: openai
  model: gpt-4o
  temperature: 0.7
  max_tokens: 1000
  provider_settings:
    openai:
      # API key will be loaded from environment variables:
      # 1. OPENAI_API_KEY
      # 2. TESTRONAUT_LLM_API_KEY
      api_key: null
      organization: null
      base_url: null
      models:
        default: gpt-4o
        chat: gpt-4o
        json: gpt-4o-mini
        embedding: text-embedding-3-small
    anthropic:
      # API key will be loaded from environment variables:
      # 1. ANTHROPIC_API_KEY
      # 2. TESTRONAUT_LLM_API_KEY
      api_key: null
      base_url: null
      models:
        default: claude-3-sonnet-20240229
        chat: claude-3-sonnet-20240229
        json: claude-3-opus-20240229
    mock:
      # Mock provider doesn't need any special settings

# Test execution settings
execution:
  timeout: 60
  work_dir: null
  use_docker: true
  docker_image: ubuntu:latest
  parallel_tests: 1
