# Testronaut default configuration

app_name: Testronaut
debug: false
config_dir: ~/.testronaut

# Logging settings
logging:
  level: INFO
  format: structured
  output_file: null
  json_output: false

# Database settings
database:
  url: sqlite:///testronaut.db
  echo: false
  pool_size: 5
  pool_recycle: 3600

# LLM settings
llm:
  provider: openai
  api_key: null # Set via TESTRONAUT_LLM_API_KEY environment variable
  model: gpt-4o
  temperature: 0.7
  max_tokens: 1000

# Test execution settings
execution:
  timeout: 60
  work_dir: null
  use_docker: true
  docker_image: ubuntu:latest
  parallel_tests: 1
